application: gbl-watcher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /_api/hasChanged
  script: web.app
  login: admin

- url: /_api/send
  script: web.app
  login: admin

- url: /_api/.*
  script: web.app

- url: /(.*)
  static_files: static/index.html
  upload: static/index.html

